project:
  type: website
  output-dir: docs

website:
  title: "figures-in-ggplot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: crab-plot-workshop.qmd
        text: Theme customization

format:
  html:
    theme: minty
    css: styles.css
    toc: true



